export const designPosts = [
  {
    id: "watermelon-ui",
    title: "Watermelon UI",
    description: "Fresh, vibrant, rounded UI trend of 2025.",
    content: `Watermelon UI is inspired by juicy pink-red and mint tones, bubbly rounded cards, and soft shadows. It's great for youthful or modern app design with personality.`,
    tag: "UI/UX",
    image: "watermellon_eqzvp0",
  },
  {
    id: "glassmorphism-design",
    title: "Glassmorphism in Interfaces",
    description: "Frosted-glass effect with translucent UI layers.",
    content: `Glassmorphism uses background blur, transparency, and depth layering to create elegant UI designs. Popularized by macOS Big Sur, it’s used in modern dashboards and modals.`,
    tag: "UI/UX",
    image: "cld-sample-3",
  },
  {
    id: "neumorphism-effect",
    title: "Neumorphism in Components",
    description: "Soft, 3D-like UI design with inner shadows.",
    content: `Neumorphism creates soft, plastic-like UIs with depth by blending background colors and inset shadows. It’s perfect for minimalist control panels or settings pages.`,
    tag: "UI/UX",
    image: "cld-sample-2",
  },
  {
    id: "brutalist-ui",
    title: "Brutalist UI Aesthetics",
    description: "Unpolished, bold design inspired by raw architecture.",
    content: `Brutalism in UI uses bold fonts, high-contrast blocks, and raw layouts that defy modern polish. It’s edgy and sometimes polarizing but can stand out strongly.`,
    tag: "UI/UX",
    image: "dessert-on-a-plate",
  },
  {
    id: "minimalist-ui",
    title: "Minimalist UI",
    description: "Less is more — the power of whitespace and clarity.",
    content: `Minimalism emphasizes simplicity, hierarchy, and focus. Using lots of white space, basic typography, and subtle motion, minimalist UIs help users focus on what matters.`,
    tag: "UI/UX",
    image: "cup-on-a-table",
  },
  {
    id: "dark-mode-ui",
    title: "Dark Mode in Design",
    description: "Comfortable, battery-saving and elegant.",
    content: `Dark Mode isn’t just trendy — it reduces eye strain and improves readability in low light. Modern UI kits now include complete dark themes using CSS variables.`,
    tag: "UI/UX",
    image: "cld-sample",
  },
  {
    id: "skeuomorphic-ui",
    title: "Skeuomorphism Returns?",
    description: "Real-world textures and design realism.",
    content: `Skeuomorphism tries to replicate real-world materials like leather or glass. While out of trend for years, it's now seeing a creative resurgence in retro design circles.`,
    tag: "UI/UX",
    image: "cld-sample-2",
  },
  {
    id: "mobile-first-design",
    title: "Mobile-First UX Thinking",
    description: "Design with small screens in mind — first.",
    content: `Designing for mobile first ensures layout simplicity, better performance, and accessibility. It forces decisions on priority and clarity before scaling up for desktops.`,
    tag: "UI/UX",
    image: "planting_pfp7jp",
  },
  {
    id: "microinteractions",
    title: "Designing Microinteractions",
    description: "Small animations that create big delight.",
    content: `Microinteractions are subtle UI animations: a like button bounce, a hover glow, a loading pulse. They improve feedback and make UIs feel alive and intuitive.`,
    tag: "UI/UX",
    image: "tailwind-react_pjac6u",
  },
  {
    id: "3d-css-design",
    title: "3D UI using CSS",
    description: "Depth and rotation effects with pure CSS.",
    content: `CSS transforms and perspective properties now let you create 3D UI panels and flip cards — great for portfolios, dashboards, and interactive storytelling apps.`,
    tag: "UI/UX",
    image: "watermellon_eqzvp0",
  },
];