export const techPosts = [
  {
    id: "react-vite-tailwind",
    title: "React + Vite + TailwindCSS",
    description: "The modern frontend stack for lightning-fast UI development.",
    content: `This trio is a go-to combo for many developers...`,
    tag: "Tech",
    image: "cld-sample-3", // Reused from designPosts
  },
  {
    id: "nextjs-typescript-tailwind",
    title: "Next.js + TypeScript + Tailwind",
    description: "Build scalable apps with type safety and server-side rendering.",
    content: `With Next.js...`,
    tag: "Tech",
    image: "cld-sample-2",
  },
  {
    id: "vue-vite-pinia",
    title: "Vue 3 + Vite + Pinia",
    description: "A smooth and fast experience with modern Vue tooling.",
    content: `Vue 3's Composition API...`,
    tag: "Tech",
    image: "samples/dessert-on-a-plate",
  },
  {
    id: "sveltekit-tailwind",
    title: "SvelteKit + TailwindCSS",
    description: "Reactivity meets elegance with this fast and lean combo.",
    content: `SvelteKit offers built-in routing...`,
    tag: "Tech",
    image: "samples/cup-on-a-table",
  },
  {
    id: "react-ts-redux",
    title: "React + TypeScript + Redux Toolkit",
    description: "Scale complex apps with robust state management.",
    content: `Redux Toolkit simplifies boilerplate...`,
    tag: "Tech",
    image: "cld-sample",
  },
  {
    id: "astro-tailwind-mdx",
    title: "Astro + Tailwind + MDX",
    description: "Build static sites using components and markdown together.",
    content: `Astro lets you ship less JS...`,
    tag: "Tech",
    image: "cld-sample-2",
  },
  {
    id: "react-native-expo",
    title: "React Native + Expo",
    description: "Build cross-platform mobile apps using JavaScript.",
    content: `With Expo simplifying configuration...`,
    tag: "Tech",
    image: "planting_pfp7jp",
  },
  {
    id: "vite-vanillajs-tailwind",
    title: "Vite + VanillaJS + Tailwind",
    description: "A modern, no-framework dev stack with performance in mind.",
    content: `Sometimes you don’t need React...`,
    tag: "Tech",
    image: "tailwind-react_pjac6u",
  },
  {
    id: "remix-typescript",
    title: "Remix + TypeScript",
    description: "Leverage data-fetching and routes with full-stack rendering.",
    content: `Remix brings server-side rendering...`,
    tag: "Tech",
    image: "watermellon_eqzvp0",
  },
  {
    id: "solidjs-tailwind",
    title: "SolidJS + TailwindCSS",
    description: "Ultra-fast fine-grained reactivity meets utility-first CSS.",
    content: `SolidJS compiles to minimal JS...`,
    tag: "Tech",
    image: "cld-sample-3",
  },
];